return {
    {
        "WhoIsSethDaniel/mason-tool-installer.nvim",
        event = "VeryLazy",
        dependencies = {
            "williamboman/mason.nvim",
        },
        config = function()
            require("mason-tool-installer").setup {
                ensure_installed = {
                    "autopep8",
                    "basedpyright",
                    "bash-language-server",
                    "buf",
                    "checkstyle",
                    "debugpy",
                    "delve",
                    "eslint_d",
                    "gofumpt",
                    "goimports",
                    "golangci-lint",
                    "golines",
                    "gomodifytags",
                    "gopls",
                    "gotestsum",
                    "isort",
                    "java-debug-adapter",
                    "java-test",
                    "jdtls",
                    "jsonlint",
                    "kotlin-lsp",
                    "lua-language-server",
                    "luacheck",
                    "markdownlint",
                    "mdsf",
                    "prettier",
                    "protolint",
                    "pylint",
                    "ruff",
                    "sqlfluff",
                    "stylelint",
                    "stylua",
                    "typescript-language-server",
                    "yamllint",
                },
                start_delay = 0,
            }
        end,
    },
}
