service_tier = "fast"
[features]
apps = false
plugins = false

[tui]
vim_mode_default = true
notifications = true
notification_method = "bel"
notification_condition = "always"
status_line = ["model-with-reasoning", "current-dir", "five-hour-limit", "weekly-limit", "context-remaining"]
session_picker_view = "comfortable"
pet = "disabled"

[mcp_servers.singularity]
command = "/Users/ilyasyoy/go/bin/singularity-mcp"
env_vars = ["SINGULARITY_TOKEN"]
startup_timeout_sec = 10
enabled = false

[projects."/Users/ilyasyoy/Projects/IlyasYOY/singularity-mcp"]
trust_level = "trusted"

[projects."/Users/ilyasyoy/Projects/IlyasYOY/spellfix.nvim"]
trust_level = "trusted"

[projects."/Users/ilyasyoy/Projects/IlyasYOY/IlyasYOY"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.6-sol" = 4
